import ProjectDescription

let workspace = Workspace(
    name: "TinyMetronome",
    projects: [
        "TinyMetronome",
    ],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .enabled(codeCoverageMode: .all)
    )
)
